projects:
  frontend:
    schema:
      - "backend/api.generated.gql"
      - "frontend/schemas/*.gql"
    include:
      - "frontend/**/*.gql"
    documents:
      - "frontend/**/*.gql"
    extensions:
      customDirectives:
        - directive @client on FIELD
