packageExtensions:
  "@prisma/engine-core@*":
    dependencies:
      strip-ansi: ^6.0.0
  koa-pino-logger@*:
    peerDependencies:
      pino-pretty: "*"
  pino-http@*:
    peerDependencies:
      pino-pretty: "*"
  pino@*:
    peerDependencies:
      pino-pretty: "*"
  "@anatine/esbuild-decorators@*":
    dependencies:
      tslib: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-2.4.2.cjs
