packageExtensions:
  "@chakra-ui/accordion@*":
    peerDependencies:
      framer-motion: "*"
  "@chakra-ui/anatomy@*":
    peerDependencies:
      "@chakra-ui/system": "*"
  "@chakra-ui/skeleton@*":
    peerDependencies:
      "@chakra-ui/theme": "*"
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@chakra-ui/switch@*":
    peerDependencies:
      framer-motion: "*"
  "@prisma/engine-core@*":
    peerDependencies:
      strip-ansi: "*"
  koa-views@*:
    peerDependencies:
      ejs: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpEnableEsmLoader: false

yarnPath: .yarn/releases/yarn-3.2.0-rc.6.cjs
