packageExtensions:
  "@prisma/engine-core@*":
    peerDependencies:
      strip-ansi: "*"
  koa-pino-logger@*:
    peerDependencies:
      pino-pretty: "*"
  pino-http@*:
    peerDependencies:
      pino-pretty: "*"
  pino@*:
    peerDependencies:
      pino-pretty: "*"
  "@anatine/esbuild-decorators@*":
    dependencies:
      tslib: "*"
  "@graphql-codegen/plugin-helpers@*":
    dependencies:
      "@graphql-codegen/visitor-plugin-common": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-2.4.2.cjs
