packageExtensions:
  "@graphql-codegen/plugin-helpers@^2.0.0":
    dependencies:
      "@graphql-codegen/visitor-plugin-common": "^2.0.0"
  "@prisma/engine-core@*":
    peerDependencies:
      strip-ansi: "*"
  "@chakra-ui/provider@*":
    peerDependencies:
      "@chakra-ui/portal": "*"
      "@chakra-ui/react-env": "*"
  "@chakra-ui/accordion@*":
    peerDependencies:
      "framer-motion": "*"
  "@chakra-ui/switch@*":
    peerDependencies:
      "framer-motion": "*"
  "@chakra-ui/skeleton@*":
    peerDependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
