query GetUsers {
	users {
		id
		profile
		email
		lastName
	}
}

subscription UserProfileUpdate($id: String!) {
	userProfileUpdate(id: $id) {
		...UserProfile
	}
}

mutation UpdateUserProfile(
	$data: UserProfileUpdateInput!
	$where: UserWhereUniqueInput!
) {
	updateUserProfile(data: $data, where: $where) {
		...UserProfile
	}
}
